services:
  - type: web
    name: salimtrading-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: true
    region: oregon
